package ui;

import data.ActivitySheet;
import listener.AddActivityListener;

import javax.swing.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import static util.DateTimeFormats.MONTH_DAY_YEAR_FORMAT;

public class ActivitySheetHeader {
	private JLabel dateLabel;
	private JLabel agentLabel;
	private JLabel officeLabel;
	private JButton addActivityButton;
	private JPanel mainPanel;
	private ActivitySheet activitySheet;

	public ActivitySheetHeader() {
		addActivityButton.addActionListener(new AddActivityListener());
	}

	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridBagLayout());
		mainPanel.setMaximumSize(new Dimension(2147483647, 60));
		mainPanel.setMinimumSize(new Dimension(400, 60));
		mainPanel.setPreferredSize(new Dimension(400, 60));
		dateLabel = new JLabel();
		dateLabel.setHorizontalAlignment(10);
		dateLabel.setText("Label");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		mainPanel.add(dateLabel, gbc);
		agentLabel = new JLabel();
		agentLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		mainPanel.add(agentLabel, gbc);
		officeLabel = new JLabel();
		officeLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		mainPanel.add(officeLabel, gbc);
		addActivityButton = new JButton();
		addActivityButton.setText("+");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.gridheight = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		mainPanel.add(addActivityButton, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		mainPanel.add(spacer1, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		mainPanel.add(spacer2, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}

	public void setData(ActivitySheet activitySheet) {
		this.activitySheet = activitySheet;
		dateLabel.setText("Date: " + MONTH_DAY_YEAR_FORMAT.print(activitySheet.getDate()));
		agentLabel.setText("Agent: " + activitySheet.getAgent().getNameAndId());
		officeLabel.setText("Office: " + activitySheet.getOffice().getCity() + ", " + activitySheet.getOffice().getState());
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}
}
